### ISSUE TITLE
Bug pip install gmsh-sdk on Mac

### ISSUE THREAD

**Issue by louisleroy5** [mrkwjc/gmsh-sdk#6] opened 2020-02-17 18:31 UTC
Hi,

When installing gmsh-sdk on my Mac (macOS Mojave 10.14.6) with the pip install command, the download never completes (see screenshot of the Terminal in attachment please.). I would like to know if there is a solution to this issue, because I know for a fact that one of my colleagues has the same issue.

<img width="572" alt="install gmsh-sdk" src="https://user-images.githubusercontent.com/36041802/74678539-48aeb500-5189-11ea-8c8e-1f006bba5dcb.png">

**Comment by mrkwjc** [comment] 2020-02-17 21:22
Hi! Unfortunately i have similar problem on Linux with current git verison (4.5.2). The problem is here:
```
from urllib.request import urlopen
sdk = urlopen(url).read()
```
where `url` is a link to SDK file, e.g. http://gmsh.info/bin/MacOSX/gmsh-4.5.2-MacOSX-sdk.tgz . Somehow lately this download never ends (althought it works in browsers) and this is a mystery to me. Setting for example Mozilla headers in python's request didn't help... Any ideas?

Currently you can try to install earlier version of gmsk-sdk, e.g.:
```
pip install gmsh-sdk==4.5.0.post1
```

**Comment by stsve** [comment] 2020-02-18 15:27
Hello, 
I also have the same problem for the gmsh module download (macOS Catalina 10.15.3).
I tried to download the earlier version as you suggested but I still get the never ending download:

<img width="387" alt="Screen Shot 2020-02-18 at 10 24 07 AM" src="https://user-images.githubusercontent.com/61162175/74750033-0e045580-5239-11ea-8d08-998e3e91d0a8.png">

I thought it could be linked with the non identified developers shield macOS has, but even when overiding this with:`sudo spctl --master-enable` the download never ends

**Comment by mrkwjc** [comment] 2020-02-18 16:35
Asked a question at stackoverflow: https://stackoverflow.com/questions/60285495/python-why-urllib-request-urlopen-read-never-finishes-download.

**Comment by mrkwjc** [comment] 2020-02-22 22:27
Because of no luck with `urllib` i switched to `requests` library. However if it is not present in the system (usually it is) you must install it before gmsh-sdk. Try now
```
pip install requests
pip install --upgrade gmsh-sdk
```

**Comment by stsve** [comment] 2020-02-22 22:30
Excellent! It works!

<img width="280" alt="Screen Shot 2020-02-22 at 5 30 30 PM" src="https://user-images.githubusercontent.com/61162175/75100230-0e825080-5599-11ea-9f2e-5d96387eaa89.png">

**Comment by mrkwjc** [comment] 2020-02-22 22:33
Nice, closing then.

**Closed as completed by mrkwjc** 2020-02-22 22:33 UTC
